//===----------------------------------------------------------------------===//
//
// This source file is part of the Soto for AWS open source project
//
// Copyright (c) 2017-2024 the Soto project authors
// Licensed under Apache License v2.0
//
// See LICENSE.txt for license information
// See CONTRIBUTORS.txt for the list of Soto project authors
//
// SPDX-License-Identifier: Apache-2.0
//
//===----------------------------------------------------------------------===//

// THIS FILE IS AUTOMATICALLY GENERATED by https://github.com/soto-project/soto-codegenerator.
// DO NOT EDIT.

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
@_spi(SotoInternal) import SotoCore

extension SESv2 {
    // MARK: Enums

    public enum AttachmentContentDisposition: String, CustomStringConvertible,
        Codable, Sendable, CodingKeyRepresentable
    {
        case attachment = "ATTACHMENT"
        case inline = "INLINE"
        public var description: String { return self.rawValue }
    }

    public enum AttachmentContentTransferEncoding: String,
        CustomStringConvertible, Codable, Sendable, CodingKeyRepresentable
    {
        case base64 = "BASE64"
        case quotedPrintable = "QUOTED_PRINTABLE"
        case sevenBit = "SEVEN_BIT"
        public var description: String { return self.rawValue }
    }

    // MARK: Shapes

    public struct Attachment: AWSEncodableShape {
        ///  A brief description of the attachment content.
        public let contentDescription: String?
        ///  A standard descriptor indicating how the attachment should be rendered in the email. Supported values: ATTACHMENT or INLINE.
        public let contentDisposition: AttachmentContentDisposition?
        ///  Unique identifier for the attachment, used for referencing attachments with INLINE disposition in HTML content.
        public let contentId: String?
        ///  Specifies how the attachment is encoded. Supported values: BASE64, QUOTED_PRINTABLE, SEVEN_BIT.
        public let contentTransferEncoding: AttachmentContentTransferEncoding?
        ///  The MIME type of the attachment.  Example: application/pdf, image/jpeg
        public let contentType: String?
        /// The file name for the attachment as it will appear in the email. Amazon SES restricts certain file extensions. To ensure attachments are accepted, check the Unsupported attachment types in the Amazon SES Developer Guide.
        public let fileName: String
        ///  The raw data of the attachment. It needs to be base64-encoded if you are accessing Amazon SES directly through the HTTPS interface. If you are accessing Amazon SES using an Amazon Web Services SDK, the SDK takes care of the base 64-encoding for you.
        public let rawContent: AWSBase64Data

        @inlinable
        public init(
            contentDescription: String? = nil,
            contentDisposition: AttachmentContentDisposition? = nil,
            contentId: String? = nil,
            contentTransferEncoding: AttachmentContentTransferEncoding? = nil,
            contentType: String? = nil,
            fileName: String,
            rawContent: AWSBase64Data
        ) {
            self.contentDescription = contentDescription
            self.contentDisposition = contentDisposition
            self.contentId = contentId
            self.contentTransferEncoding = contentTransferEncoding
            self.contentType = contentType
            self.fileName = fileName
            self.rawContent = rawContent
        }

        public func validate(name: String) throws {
            try self.validate(
                self.contentDescription,
                name: "contentDescription",
                parent: name,
                max: 1000
            )
            try self.validate(
                self.contentId,
                name: "contentId",
                parent: name,
                max: 78
            )
            try self.validate(
                self.contentId,
                name: "contentId",
                parent: name,
                min: 1
            )
            try self.validate(
                self.contentType,
                name: "contentType",
                parent: name,
                max: 78
            )
            try self.validate(
                self.contentType,
                name: "contentType",
                parent: name,
                min: 1
            )
            try self.validate(
                self.fileName,
                name: "fileName",
                parent: name,
                max: 255
            )
        }

        private enum CodingKeys: String, CodingKey {
            case contentDescription = "ContentDescription"
            case contentDisposition = "ContentDisposition"
            case contentId = "ContentId"
            case contentTransferEncoding = "ContentTransferEncoding"
            case contentType = "ContentType"
            case fileName = "FileName"
            case rawContent = "RawContent"
        }
    }

    public struct Body: AWSEncodableShape {
        /// An object that represents the version of the message that is displayed in email clients that support HTML. HTML messages can include formatted text, hyperlinks, images, and more.
        public let html: Content?
        /// An object that represents the version of the message that is displayed in email clients that don't support HTML, or clients where the recipient has disabled HTML rendering.
        public let text: Content?

        @inlinable
        public init(html: Content? = nil, text: Content? = nil) {
            self.html = html
            self.text = text
        }

        private enum CodingKeys: String, CodingKey {
            case html = "Html"
            case text = "Text"
        }
    }

    public struct Content: AWSEncodableShape {
        /// The character set for the content. Because of the constraints of the SMTP protocol, Amazon SES uses 7-bit ASCII by default. If the text includes characters outside of the ASCII range, you have to specify a character set. For example, you could specify UTF-8, ISO-8859-1, or Shift_JIS.
        public let charset: String?
        /// The content of the message itself.
        public let data: String

        @inlinable
        public init(charset: String? = nil, data: String) {
            self.charset = charset
            self.data = data
        }

        private enum CodingKeys: String, CodingKey {
            case charset = "Charset"
            case data = "Data"
        }
    }

    public struct Destination: AWSEncodableShape {
        /// An array that contains the email addresses of the "BCC" (blind carbon copy) recipients for the email.
        public let bccAddresses: [String]?
        /// An array that contains the email addresses of the "CC" (carbon copy) recipients for the email.
        public let ccAddresses: [String]?
        /// An array that contains the email addresses of the "To" recipients for the email.
        public let toAddresses: [String]?

        @inlinable
        public init(
            bccAddresses: [String]? = nil,
            ccAddresses: [String]? = nil,
            toAddresses: [String]? = nil
        ) {
            self.bccAddresses = bccAddresses
            self.ccAddresses = ccAddresses
            self.toAddresses = toAddresses
        }

        private enum CodingKeys: String, CodingKey {
            case bccAddresses = "BccAddresses"
            case ccAddresses = "CcAddresses"
            case toAddresses = "ToAddresses"
        }
    }

    public struct EmailContent: AWSEncodableShape {
        /// The raw email message. The message has to meet the following criteria:   The message has to contain a header and a body, separated by one blank line.   All of the required header fields must be present in the message.   Each part of a multipart MIME message must be formatted properly.   If you include attachments, they must be in a file format that the Amazon SES API v2 supports.    The raw data of the message needs to base64-encoded if you are accessing Amazon SES directly through the HTTPS interface. If you are accessing Amazon SES using an Amazon Web Services SDK, the SDK takes care of the base 64-encoding for you.   If any of the MIME parts in your message contain content that is outside of the 7-bit ASCII character range, you should encode that content to ensure that recipients' email clients render the message properly.   The length of any single line of text in the message can't exceed 1,000 characters. This restriction is defined in RFC 5321.
        public let raw: RawMessage?
        /// The simple email message. The message consists of a subject, message body and attachments list.
        public let simple: Message?
        /// The template to use for the email message.
        public let template: Template?

        @inlinable
        public init(
            raw: RawMessage? = nil,
            simple: Message? = nil,
            template: Template? = nil
        ) {
            self.raw = raw
            self.simple = simple
            self.template = template
        }

        public func validate(name: String) throws {
            try self.simple?.validate(name: "\(name).simple")
            try self.template?.validate(name: "\(name).template")
        }

        private enum CodingKeys: String, CodingKey {
            case raw = "Raw"
            case simple = "Simple"
            case template = "Template"
        }
    }

    public struct EmailTemplateContent: AWSEncodableShape {
        /// The HTML body of the email.
        public let html: String?
        /// The subject line of the email.
        public let subject: String?
        /// The email body that will be visible to recipients whose email clients do not display HTML.
        public let text: String?

        @inlinable
        public init(
            html: String? = nil,
            subject: String? = nil,
            text: String? = nil
        ) {
            self.html = html
            self.subject = subject
            self.text = text
        }

        private enum CodingKeys: String, CodingKey {
            case html = "Html"
            case subject = "Subject"
            case text = "Text"
        }
    }

    public struct ListManagementOptions: AWSEncodableShape {
        /// The name of the contact list.
        public let contactListName: String
        /// The name of the topic.
        public let topicName: String?

        @inlinable
        public init(contactListName: String, topicName: String? = nil) {
            self.contactListName = contactListName
            self.topicName = topicName
        }

        private enum CodingKeys: String, CodingKey {
            case contactListName = "ContactListName"
            case topicName = "TopicName"
        }
    }

    public struct Message: AWSEncodableShape {
        ///  The List of attachments to include in your email. All recipients will receive the same attachments.
        public let attachments: [Attachment]?
        /// The body of the message. You can specify an HTML version of the message, a text-only version of the message, or both.
        public let body: Body
        /// The list of message headers that will be added to the email message.
        public let headers: [MessageHeader]?
        /// The subject line of the email. The subject line can only contain 7-bit ASCII characters. However, you can specify non-ASCII characters in the subject line by using encoded-word syntax, as described in RFC 2047.
        public let subject: Content

        @inlinable
        public init(
            attachments: [Attachment]? = nil,
            body: Body,
            headers: [MessageHeader]? = nil,
            subject: Content
        ) {
            self.attachments = attachments
            self.body = body
            self.headers = headers
            self.subject = subject
        }

        public func validate(name: String) throws {
            try self.attachments?
                .forEach {
                    try $0.validate(name: "\(name).attachments[]")
                }
            try self.headers?
                .forEach {
                    try $0.validate(name: "\(name).headers[]")
                }
            try self.validate(
                self.headers,
                name: "headers",
                parent: name,
                max: 15
            )
        }

        private enum CodingKeys: String, CodingKey {
            case attachments = "Attachments"
            case body = "Body"
            case headers = "Headers"
            case subject = "Subject"
        }
    }

    public struct MessageHeader: AWSEncodableShape {
        /// The name of the message header. The message header name has to meet the following criteria:   Can contain any printable ASCII character (33 - 126) except for colon (:).   Can contain no more than 126 characters.
        public let name: String
        /// The value of the message header. The message header value has to meet the following criteria:   Can contain any printable ASCII character.   Can contain no more than 870 characters.
        public let value: String

        @inlinable
        public init(name: String, value: String) {
            self.name = name
            self.value = value
        }

        public func validate(name: String) throws {
            try self.validate(self.name, name: "name", parent: name, max: 126)
            try self.validate(self.name, name: "name", parent: name, min: 1)
            try self.validate(
                self.name,
                name: "name",
                parent: name,
                pattern: "^[!-9;-@A-~]+$"
            )
            try self.validate(self.value, name: "value", parent: name, max: 870)
            try self.validate(self.value, name: "value", parent: name, min: 1)
            try self.validate(
                self.value,
                name: "value",
                parent: name,
                pattern: "^[ -~]*$"
            )
        }

        private enum CodingKeys: String, CodingKey {
            case name = "Name"
            case value = "Value"
        }
    }

    public struct MessageTag: AWSEncodableShape {
        /// The name of the message tag. The message tag name has to meet the following criteria:   It can only contain ASCII letters (a–z, A–Z), numbers (0–9), underscores (_), or dashes (-).   It can contain no more than 256 characters.
        public let name: String
        /// The value of the message tag. The message tag value has to meet the following criteria:   It can only contain ASCII letters (a–z, A–Z), numbers (0–9), underscores (_), or dashes (-).   It can contain no more than 256 characters.
        public let value: String

        @inlinable
        public init(name: String, value: String) {
            self.name = name
            self.value = value
        }

        private enum CodingKeys: String, CodingKey {
            case name = "Name"
            case value = "Value"
        }
    }

    public struct RawMessage: AWSEncodableShape {
        /// The raw email message. The message has to meet the following criteria:   The message has to contain a header and a body, separated by one blank line.   All of the required header fields must be present in the message.   Each part of a multipart MIME message must be formatted properly.   Attachments must be in a file format that the Amazon SES supports.   The raw data of the message needs to base64-encoded if you are accessing Amazon SES directly through the HTTPS interface. If you are accessing Amazon SES using an Amazon Web Services SDK, the SDK takes care of the base 64-encoding for you.   If any of the MIME parts in your message contain content that is outside of the 7-bit ASCII character range, you should encode that content to ensure that recipients' email clients render the message properly.   The length of any single line of text in the message can't exceed 1,000 characters. This restriction is defined in RFC 5321.
        public let data: AWSBase64Data

        @inlinable
        public init(data: AWSBase64Data) {
            self.data = data
        }

        private enum CodingKeys: String, CodingKey {
            case data = "Data"
        }
    }

    public struct SendEmailRequest: AWSEncodableShape {
        /// The name of the configuration set to use when sending the email.
        public let configurationSetName: String?
        /// An object that contains the body of the message. You can send either a Simple message, Raw message, or a Templated message.
        public let content: EmailContent
        /// An object that contains the recipients of the email message.
        public let destination: Destination?
        /// A list of tags, in the form of name/value pairs, to apply to an email that you send using the SendEmail operation. Tags correspond to characteristics of the email that you define, so that you can publish email sending events.
        public let emailTags: [MessageTag]?
        /// The ID of the multi-region endpoint (global-endpoint).
        public let endpointId: String?
        /// The address that you want bounce and complaint notifications to be sent to.
        public let feedbackForwardingEmailAddress: String?
        /// This parameter is used only for sending authorization. It is the ARN of the identity that is associated with the sending authorization policy that permits you to use the email address specified in the FeedbackForwardingEmailAddress parameter. For example, if the owner of example.com (which has ARN arn:aws:ses:us-east-1:123456789012:identity/example.com) attaches a policy to it that authorizes you to use feedback@example.com, then you would specify the FeedbackForwardingEmailAddressIdentityArn to be arn:aws:ses:us-east-1:123456789012:identity/example.com, and the FeedbackForwardingEmailAddress to be feedback@example.com. For more information about sending authorization, see the Amazon SES Developer Guide.
        public let feedbackForwardingEmailAddressIdentityArn: String?
        /// The email address to use as the "From" address for the email. The address that you specify has to be verified.
        public let fromEmailAddress: String?
        /// This parameter is used only for sending authorization. It is the ARN of the identity that is associated with the sending authorization policy that permits you to use the email address specified in the FromEmailAddress parameter. For example, if the owner of example.com (which has ARN arn:aws:ses:us-east-1:123456789012:identity/example.com) attaches a policy to it that authorizes you to use sender@example.com, then you would specify the FromEmailAddressIdentityArn to be arn:aws:ses:us-east-1:123456789012:identity/example.com, and the FromEmailAddress to be sender@example.com. For more information about sending authorization, see the Amazon SES Developer Guide. For Raw emails, the FromEmailAddressIdentityArn value overrides the X-SES-SOURCE-ARN and X-SES-FROM-ARN headers specified in raw email message content.
        public let fromEmailAddressIdentityArn: String?
        /// An object used to specify a list or topic to which an email belongs, which will be used when a contact chooses to unsubscribe.
        public let listManagementOptions: ListManagementOptions?
        /// The "Reply-to" email addresses for the message. When the recipient replies to the message, each Reply-to address receives the reply.
        public let replyToAddresses: [String]?
        /// The name of the tenant through which this email will be sent.  The email sending operation will only succeed if all referenced resources (identities, configuration sets, and templates) are associated with this tenant.
        public let tenantName: String?

        @inlinable
        public init(
            configurationSetName: String? = nil,
            content: EmailContent,
            destination: Destination? = nil,
            emailTags: [MessageTag]? = nil,
            endpointId: String? = nil,
            feedbackForwardingEmailAddress: String? = nil,
            feedbackForwardingEmailAddressIdentityArn: String? = nil,
            fromEmailAddress: String? = nil,
            fromEmailAddressIdentityArn: String? = nil,
            listManagementOptions: ListManagementOptions? = nil,
            replyToAddresses: [String]? = nil,
            tenantName: String? = nil
        ) {
            self.configurationSetName = configurationSetName
            self.content = content
            self.destination = destination
            self.emailTags = emailTags
            self.endpointId = endpointId
            self.feedbackForwardingEmailAddress = feedbackForwardingEmailAddress
            self.feedbackForwardingEmailAddressIdentityArn =
                feedbackForwardingEmailAddressIdentityArn
            self.fromEmailAddress = fromEmailAddress
            self.fromEmailAddressIdentityArn = fromEmailAddressIdentityArn
            self.listManagementOptions = listManagementOptions
            self.replyToAddresses = replyToAddresses
            self.tenantName = tenantName
        }

        public func validate(name: String) throws {
            try self.content.validate(name: "\(name).content")
            try self.validate(
                self.feedbackForwardingEmailAddressIdentityArn,
                name: "feedbackForwardingEmailAddressIdentityArn",
                parent: name,
                min: 1
            )
            try self.validate(
                self.fromEmailAddressIdentityArn,
                name: "fromEmailAddressIdentityArn",
                parent: name,
                min: 1
            )
            try self.validate(
                self.tenantName,
                name: "tenantName",
                parent: name,
                min: 1
            )
        }

        private enum CodingKeys: String, CodingKey {
            case configurationSetName = "ConfigurationSetName"
            case content = "Content"
            case destination = "Destination"
            case emailTags = "EmailTags"
            case endpointId = "EndpointId"
            case feedbackForwardingEmailAddress =
                "FeedbackForwardingEmailAddress"
            case feedbackForwardingEmailAddressIdentityArn =
                "FeedbackForwardingEmailAddressIdentityArn"
            case fromEmailAddress = "FromEmailAddress"
            case fromEmailAddressIdentityArn = "FromEmailAddressIdentityArn"
            case listManagementOptions = "ListManagementOptions"
            case replyToAddresses = "ReplyToAddresses"
            case tenantName = "TenantName"
        }
    }

    public struct SendEmailResponse: AWSDecodableShape {
        /// A unique identifier for the message that is generated when the message is accepted.  It's possible for Amazon SES to accept a message without sending it. For example, this can happen when the message that you're trying to send has an attachment that contains a virus, or when you send a templated email that contains invalid personalization content.
        public let messageId: String?

        @inlinable
        public init(messageId: String? = nil) {
            self.messageId = messageId
        }

        private enum CodingKeys: String, CodingKey {
            case messageId = "MessageId"
        }
    }

    public struct Template: AWSEncodableShape {
        ///  The List of attachments to include in your email. All recipients will receive the same attachments.
        public let attachments: [Attachment]?
        /// The list of message headers that will be added to the email message.
        public let headers: [MessageHeader]?
        /// The Amazon Resource Name (ARN) of the template.
        public let templateArn: String?
        /// The content of the template.  Amazon SES supports only simple substitions when you send email using the   SendEmail or SendBulkEmail operations and  you provide the full template content in the request.
        public let templateContent: EmailTemplateContent?
        /// An object that defines the values to use for message variables in the template. This object is a set of key-value pairs. Each key defines a message variable in the template. The corresponding value defines the value to use for that variable.
        public let templateData: String?
        /// The name of the template. You will refer to this name when you send email using the SendEmail or SendBulkEmail operations.
        public let templateName: String?

        @inlinable
        public init(
            attachments: [Attachment]? = nil,
            headers: [MessageHeader]? = nil,
            templateArn: String? = nil,
            templateContent: EmailTemplateContent? = nil,
            templateData: String? = nil,
            templateName: String? = nil
        ) {
            self.attachments = attachments
            self.headers = headers
            self.templateArn = templateArn
            self.templateContent = templateContent
            self.templateData = templateData
            self.templateName = templateName
        }

        public func validate(name: String) throws {
            try self.attachments?
                .forEach {
                    try $0.validate(name: "\(name).attachments[]")
                }
            try self.headers?
                .forEach {
                    try $0.validate(name: "\(name).headers[]")
                }
            try self.validate(
                self.headers,
                name: "headers",
                parent: name,
                max: 15
            )
            try self.validate(
                self.templateArn,
                name: "templateArn",
                parent: name,
                min: 1
            )
            try self.validate(
                self.templateData,
                name: "templateData",
                parent: name,
                max: 262144
            )
            try self.validate(
                self.templateName,
                name: "templateName",
                parent: name,
                min: 1
            )
        }

        private enum CodingKeys: String, CodingKey {
            case attachments = "Attachments"
            case headers = "Headers"
            case templateArn = "TemplateArn"
            case templateContent = "TemplateContent"
            case templateData = "TemplateData"
            case templateName = "TemplateName"
        }
    }
}

// MARK: - Errors

/// Error enum for SESv2
public struct SESv2ErrorType: AWSErrorType {
    enum Code: String {
        case accountSuspendedException = "AccountSuspendedException"
        case alreadyExistsException = "AlreadyExistsException"
        case badRequestException = "BadRequestException"
        case concurrentModificationException = "ConcurrentModificationException"
        case conflictException = "ConflictException"
        case internalServiceErrorException = "InternalServiceErrorException"
        case invalidNextTokenException = "InvalidNextTokenException"
        case limitExceededException = "LimitExceededException"
        case mailFromDomainNotVerifiedException =
            "MailFromDomainNotVerifiedException"
        case messageRejected = "MessageRejected"
        case notFoundException = "NotFoundException"
        case sendingPausedException = "SendingPausedException"
        case tooManyRequestsException = "TooManyRequestsException"
    }

    private let error: Code
    public let context: AWSErrorContext?

    /// initialize SESv2
    public init?(errorCode: String, context: AWSErrorContext) {
        guard let error = Code(rawValue: errorCode) else { return nil }
        self.error = error
        self.context = context
    }

    internal init(_ error: Code) {
        self.error = error
        self.context = nil
    }

    /// return error code string
    public var errorCode: String { self.error.rawValue }

    /// The message can't be sent because the account's ability to send email has been permanently restricted.
    public static var accountSuspendedException: Self {
        .init(.accountSuspendedException)
    }
    /// The resource specified in your request already exists.
    public static var alreadyExistsException: Self {
        .init(.alreadyExistsException)
    }
    /// The input you provided is invalid.
    public static var badRequestException: Self { .init(.badRequestException) }
    /// The resource is being modified by another operation or thread.
    public static var concurrentModificationException: Self {
        .init(.concurrentModificationException)
    }
    /// If there is already an ongoing account details update under review.
    public static var conflictException: Self { .init(.conflictException) }
    /// The request couldn't be processed because an error occurred with the Amazon SES API v2.
    public static var internalServiceErrorException: Self {
        .init(.internalServiceErrorException)
    }
    /// The specified request includes an invalid or expired token.
    public static var invalidNextTokenException: Self {
        .init(.invalidNextTokenException)
    }
    /// There are too many instances of the specified resource type.
    public static var limitExceededException: Self {
        .init(.limitExceededException)
    }
    /// The message can't be sent because the sending domain isn't verified.
    public static var mailFromDomainNotVerifiedException: Self {
        .init(.mailFromDomainNotVerifiedException)
    }
    /// The message can't be sent because it contains invalid content.
    public static var messageRejected: Self { .init(.messageRejected) }
    /// The resource you attempted to access doesn't exist.
    public static var notFoundException: Self { .init(.notFoundException) }
    /// The message can't be sent because the account's ability to send email is currently paused.
    public static var sendingPausedException: Self {
        .init(.sendingPausedException)
    }
    /// Too many requests have been made to the operation.
    public static var tooManyRequestsException: Self {
        .init(.tooManyRequestsException)
    }
}

extension SESv2ErrorType: Equatable {
    public static func == (lhs: SESv2ErrorType, rhs: SESv2ErrorType) -> Bool {
        lhs.error == rhs.error
    }
}

extension SESv2ErrorType: CustomStringConvertible {
    public var description: String {
        return "\(self.error.rawValue): \(self.message ?? "")"
    }
}
